version: '3'

services:
  site:
    image: jekyll/jekyll:3.8.6
    command: bundle exec jekyll serve --future --incremental --watch --livereload --drafts --host 0.0.0.0 --port 4000 # jekyll serve --livereload --verbose
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
      #- ./vendor/bundle:/usr/local/bundle